[versions]
jvm = "25"
kotlin = "2.4.0"
ksp = "2.3.9"
jmh-plugin = "0.7.3"
maven-publish = "0.37.0"
helidon = "4.5.0"
junit = "6.1.1"
assertj = "3.27.7"
mockito-kotlin = "6.3.0"
testcontainers = "2.0.5"
fastjson2 = "2.0.62"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jmh = { id = "me.champeau.jmh", version.ref = "jmh-plugin" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }

[libraries]
helidon-webserver = { group = "io.helidon.webserver", name = "helidon-webserver", version.ref = "helidon" }
helidon-config-yaml = { group = "io.helidon.config", name = "helidon-config-yaml", version.ref = "helidon" }
helidon-webclient = { group = "io.helidon.webclient", name = "helidon-webclient", version.ref = "helidon" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher", version.ref = "junit" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
testcontainers = { group = "org.testcontainers", name = "testcontainers", version.ref = "testcontainers" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
fastjson2-kotlin = { group = "com.alibaba.fastjson2", name = "fastjson2-kotlin", version.ref = "fastjson2" }

[bundles]
helidon = [
    "helidon-webserver",
    "helidon-config-yaml"
]