[versions]
kotlin = "2.3.0-Beta2"
helidon = "4.3.0"
assertj = "3.27.3"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
helidon-webserver = { group = "io.helidon.webserver", name = "helidon-webserver", version.ref = "helidon" }
helidon-config-yaml = { group = "io.helidon.config", name = "helidon-config-yaml", version.ref = "helidon" }
helidon-webclient = { group = "io.helidon.webclient", name = "helidon-webclient", version.ref = "helidon" }
assertj-core = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[bundles]
helidon = [
    "helidon-webserver",
    "helidon-config-yaml"
]