FROM ghcr.io/graalvm/jdk-community:25.0.0 AS buildjar
WORKDIR /build/app/stopgap
ENV GRADLE_USER_HOME=/build/.gradle
COPY gradlew ./
COPY gradle gradle
COPY build.gradle.kts settings.gradle.kts gradle.properties  ./
COPY src/main src/main
RUN --mount=type=cache,target=${GRADLE_USER_HOME} ./gradlew --no-daemon jar


FROM ghcr.io/graalvm/native-image-community:25.0.0-muslib AS buildnative
WORKDIR /build/app/stopgap
COPY --from=buildjar /build/app/stopgap/build/libs/libs libs
COPY --from=buildjar /build/app/stopgap/build/libs/stopgap.jar ./
RUN native-image --static --libc=musl -jar stopgap.jar


FROM scratch
WORKDIR /app/stopgap
COPY --from=buildnative /build/app/stopgap/stopgap ./
ENTRYPOINT ["/app/stopgap/stopgap"]
