package dev.sku20.stopgap.codegen.ast

interface AstVisitor {
    fun visitAssignment(node: AstAssignment)
    fun visitBreak(node: AstBreak)
    fun visitCall(node: AstCall)
    fun visitContinue(node: AstContinue)
    fun visitElse(node: AstElse)
    fun visitFile(node: AstFile)
    fun visitFor(node: AstFor)
    fun visitFunction(node: AstFunction)
    fun visitIf(node: AstIf)
    fun visitLambda(node: AstLambda)
    fun visitLiteral(node: AstLiteral)
    fun visitParam(node: AstParam)
    fun visitReturn(node: AstReturn)
    fun visitStringLiteral(node: AstStringLiteral)
    fun visitThrow(node: AstThrow)
    fun visitType(node: AstType)
    fun visitWhen(node: AstWhen)
    fun visitWhenBranch(node: AstWhenBranch)
    fun visitWhile(node: AstWhile)
}

fun AstVisitor.visit(node: AstExpression) = when (node) {
    is AstAssignment -> visitAssignment(node)
    is AstBreak -> visitBreak(node)
    is AstCall -> visitCall(node)
    is AstContinue -> visitContinue(node)
    is AstElse -> visitElse(node)
    is AstFile -> visitFile(node)
    is AstFor -> visitFor(node)
    is AstFunction -> visitFunction(node)
    is AstIf -> visitIf(node)
    is AstLambda -> visitLambda(node)
    is AstLiteral -> visitLiteral(node)
    is AstParam -> visitParam(node)
    is AstReturn -> visitReturn(node)
    is AstStringLiteral -> visitStringLiteral(node)
    is AstThrow -> visitThrow(node)
    is AstType -> visitType(node)
    is AstWhen -> visitWhen(node)
    is AstWhenBranch -> visitWhenBranch(node)
    is AstWhile -> visitWhile(node)
}
