name: ci.yaml

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-ci
      - run: ./gradlew test --no-daemon

  intTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-ci
      - run: ./gradlew intTest --no-daemon

  # any way to use docker cache?
  e2eTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-ci
      - run: ./gradlew e2eTestImage --no-daemon
